### ISSUE TITLE
Starting up

### ISSUE THREAD

**Issue by Noobeling** [jostasik/Flowgorithm-macOS#15]
The application doesn’t want to start up, like the window of the application doesn’t show up in my app bar.

**Comment by jostasik** [comment]
Which version of MacOS are you on? 

Apples latest update for Ventura last week temporarily broke every app that utilizes wine as a dependency. 

But I am hoping to post an updated version of Floworithm today that utilizes the newest wine update.

**Comment by Noobeling** [comment]
I'm currently on version 12.6.3
MacOS Monterey
MacBook Air 2017

**Comment by jostasik** [comment]
@AngeloAlbanesi Hey i'm sorry to hear about that :'( It's a very widespread issue although it 's looking like it should fix itself on the MacOS Venture 13.4 beta. (or at least other wine-powered applications have reported opening up again)

However if you haven't tried the new pre-release that i posted two days ago yet then feel free to try this new version that i'm working on! [Here is the link](https://github.com/jostasik/Flowgorithm-macOS/releases/tag/v3.4.2-release)

It's opening up perfectly normal on my Mac Pro but not on my laptop. So there is a 50/50 chance it opens for you. Let me know what happens if you try it!

**Comment by AngeloAlbanesi** [comment]
> Here is the link

Thank you for your response, and yes,  I have installed the new version you linked me but it doesn't work as well, maybe because I have the macbook pro m2 with apple silicon

**Comment by AngeloAlbanesi** [comment]
> @AngeloAlbanesi @Always-OnTheMoon @Noobeling Just published a new release [HERE](https://github.com/jostasik/Flowgorithm-macOS/releases/download/v3.4.2/Flowgorithm_v3.4.2.zip) that _**should**_ be working now.
> 
> However if you still have issues then you may clone the repo or download the repo as a zip [HERE](https://github.com/jostasik/Flowgorithm-macOS/archive/refs/heads/main.zip), and then run the Flowgorithm.app that results from it.

Thank you very much for your work! The app now work fine!

**Comment by jostasik** [comment]
I'm very glad to hear @AngeloAlbanesi! Please let me know if you ever run into another issue like this!

And @Noobeling , 
I am going to close this issue as completed! Every user i've heard back from after trying this latest update has been a success. Please start a new issue if your problem has not been mitigated after trying the v3.4.2 release.
